### ISSUE TITLE
What is this script doing? 

### ISSUE THREAD

**Issue by lrj0** [dschrempf/syncthing-resolve-conflicts#5]
What is this script doing and how can it help to resolve conflicts in syncthing? :)

**Comment by dschrempf** [comment]
It runs a diff program on sync conflicts that are found with updatedb. The help text in the README is very informative! Let me know if it is not clear enough, you can of course also suggest changes!

**Comment by dschrempf** [comment]
I close this issue. Feel free to reopen, if you have suggestions to improve the help!
