### ISSUE TITLE
add an option for only searching particular folder

### ISSUE THREAD

**Issue by marvinbernhardt** [dschrempf/syncthing-resolve-conflicts#6]
Especially with find the program takes much longer if there are huge folders in the home directory. I can maybe do this tomorrow. Is this also needed for locate or should it be an option for -f, i.e. -f ~/syncthing?

**Comment by dschrempf** [comment]
Thanks for your feedback. I have implemented this option (-d). Could you please check, if it also works for you?

**Comment by marvinbernhardt** [comment]
Works perfectly for me with -f (find). Thank you a lot :).
